(ns my_roguelike.roomgen-spec
  (:require [speclj.core :refer :all]
            [my_roguelike.levels.roomgens :as rooms]))

(describe "Square room generator"
          (it "should create a square room at given coords with the given size"
              (let [start-x 12
                    start-y 7
                    size 7
                    room (rooms/square-room-gen start-x start-y size)]
                (should= 49 (count room))
                (doseq [x (range start-x (+ start-x size))
                        y (range start-y (+ start-y size))]
                  (should (get room [x y])))))
          (it "should create no tiles if size is 0"
              (should= 0 (count (rooms/square-room-gen 0 0 0))))
          (it "should create no tiles if size is negative"
              (should= 0 (count (rooms/square-room-gen 1 1 -1)))))

(describe "Rectangular room generator"
          (it "should create a rectangular room at given coords with given width and height"
              (let [room-x 3
                    room-y 5
                    width 2
                    height 4
                    room (rooms/rectangle-room-gen room-x room-y width height)]
                (should= 8 (count room))
                (doseq [x (range room-x (+ room-x width))
                        y (range room-y (+ room-y height))]
                  (should (get room [x y])))))
          (it "should create no tiles if width or height is 0"
              (should= 0 (count (rooms/rectangle-room-gen 2 2 10000 0)))
              (should= 0 (count (rooms/rectangle-room-gen 3 3 0 10000))))
          (it "should create no tiles if width or height is negative"
              (should= 0 (count (rooms/rectangle-room-gen 1 1 -1 1)))
              (should= 0 (count (rooms/rectangle-room-gen 1 1 1 -1)))))

(describe "Ring room generator"
          (it "should create a room (or corridor) the shape of ring"
              (let [room (rooms/ring-room-gen 0 0 2)
                    coords [[2 -1] [0 -2] [1 1] [-1 2] [-1 -1] [-1 -2] [-2 1]
                            [-2 -1] [1 -1] [0 2] [-1 1] [2 0] [2 1] [1 2]
                            [1 -2] [-2 0]]]
                (should= 16 (count room))
                (doseq [tile room]
                  (should (some #(= % (key tile)) coords))
                  (should= :floor (:type (val tile))))))
          (it "should create just one tile to [0 0] if radius is 0"
              (should= 1 (count (rooms/ring-room-gen 0 0 0)))
              (should= [0 0] (first (keys (rooms/ring-room-gen 0 0 0))))))

(defn- test-wall-builder [& room-params]
  (let [square-room? (= 3 (count room-params))
        room-gen (if square-room?
                   rooms/square-room-gen
                   rooms/rectangle-room-gen)
        walled-room (rooms/build-walls (apply room-gen room-params))
        ox-1 (dec (first room-params))
        oy-1 (dec (second room-params))
        w+1 (inc (if square-room?
                   (last room-params)
                   (last (butlast room-params))))
        h+1 (inc (last room-params))]
    (doseq [x (range ox-1 w+1)
            y (range oy-1 h+1)]
      (if (or (or (= x ox-1) (= x w+1))
              (or (= y oy-1) (= y h+1)))
        (should= :wall (:type (get walled-room [x y])))
        (should= :floor (:type (get walled-room [x y])))))))

(describe "Wall builder"
          (it "should build walls around a square room, generated by square-room-gen"
              (test-wall-builder 1 1 3))
          (it "should build walls around a rectangular room, generated by rectangle-room-gen"
              (test-wall-builder 2 2 3 4))
          (it "should not build any walls if the room doesn't exist"
              (should= 0 (count (rooms/build-walls (rooms/rectangle-room-gen 1 1 0 0))))))
